adjetivo1 = input("Insira um adjetivo(apelido, caracteristica de algo ou alguém): ")
adjetivo2 = input("Insira um adjetivo(apelido, caracteristica de algo ou alguém): ")
adjetivo3 = input("Insira um adjetivo(apelido, caracteristica de algo ou alguém): ")
entidade1 = input("Insira uma entidade(alguém ou algo): ")
verbo1 = input("Insira um verbo que termine com ando (ação de algo ou alguém): ")

print(f"Hoje eu fui pro zoológico {adjetivo2}.")
print(f"Em uma exposição eu vi um(a) {entidade1}.")
print(f"A(o) {entidade1} era {adjetivo1} e estava {verbo1}.")
print(f"Eu era {adjetivo3}!")